[versions]
# libraries
annotations = "24.1.0"

# plugins
kotlin = "2.2.0"
changelog = "2.4.0"
intellijPlatform = "2.7.1"
qodana = "2025.1.1"
kover = "0.9.1"
nodeGradle = "7.1.0"

# Testing libraries
junit-platform = "1.14.1"
junit-jupiter = "5.14.1"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

# Testing libraries
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
nodeGradle = { id = "com.github.node-gradle.node", version.ref = "nodeGradle" }
