[versions]
# libraries
annotations = "24.1.0"

# plugins
kotlin = "2.2.0"
changelog = "2.4.0"
intellijPlatform = "2.7.1"
qodana = "2025.1.1"
kover = "0.9.1"

# Testing libraries
junit-jupiter = "5.10.2"
mockk = "1.13.8"
junit = "4.13.2"
opentest4j = "1.3.0"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

# Testing libraries
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }